### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by seanc873** [wyx827/2024USpresidentialelection#2]
Opening statement summary:
This paper uses a poll-of-polls approach to predict the voter support percentage for Kamala Harris in the 2024 U.S. presidential election. The study emphasizes the importance of factors such as pollsters' quality rating, sample size, and methodology to more accurately predict election outcomes.

Strong positive points:

- The paper includes a comprehensive description of the model used to predict the amount of support for Harris and Trump. The equation for the model, along with appropriate reasons for predictors/variables used were also provided.
- The content in the appendix is very detailed and structured properly. Each part is well-explained, and the purpose and methodology of their proposed survey is appropriate to what a standard electoral poll questionnaire would look like in the real-world.

Critical improvements needed

- Title: Please provide an appropriate title (and corresponding subtitle) for your paper. A great title and subtitle would be those which tell what the overall aim of your paper is. Ensure that the subtitle is not too long.

- Abstract: Please provide a short abstract below your title. From the [Task](https://tellingstorieswithdata.com/23-assessment.html#task) of "Telling Stories With Data" (Alexander, 2023), a great abstract would be one which summarizes your paper, reports your overall results and findings, and the significance and implications of your analysis, all typically written in four sentences.

- Structure of Paper: Please ensure that code chunks, warnings, and messages are not seen in the paper; this reduces credibility of your paper since it looks messy and unstructured. For example, code for calling libraries, such as "library(tidyverse)" should not be present. Only the final results of such code (e.g. plots, tables, and other visualizations) must be shown.

- Missing Content in Introduction and Data Sections: Please ensure that your introduction provides an overview of what question your paper aims to answer, along with necessary background literature and context. Moreover, ensure that the dataset used in this paper, along with necessary details such as its source and variables within said dataset, are stated in the "Data" section.

- References: Please make sure to add references in your actual paper! Not doing so would result in an automatic 0.

Suggestions for improvement:
Please consider:

- Removing all instances of code (whether it be code chunks or written in plain text) from the paper
- Removing unnecessary files in your repo (e.g. paper.aux)
- Adding the necessary content to different sections in your paper based on previous comments
- Discussing why this dataset was chosen (and in effect why other alternative datasets were not used) in the Data section
- Adding a section for the limitations of your study and areas for future research

Evaluation:
The Model section had some comprehensive details, and the Appendix section was very complete and done well. However, you would greatly benefit from making the changes mentioned above to improve the overall grade for your paper.

Estimated mark:
43/126

Rubric:
- R citation - 1/1
- Data citation - 0/1
- Does not look like class paper - 1/1
-  LLM usage - 0/1
-  Title - 0/2 (subtitle has a little too much detail)
- Author, date, and repo - 2/2
- Abstract - 0/4
- Introduction - 0/4
- Estimand - 0/1
- Data - 2/10
- Measurement - 0/4
- Model - 4/10
- Results - 0/10
- Discussion - 0/10
- Prose - 2/10
- Cross-references - 0/1
- Captions - 0/2
- Graphs/tables/etc - 0/4
- Idealized methodology - 10/10
- Idealized survey - 4/4
- Pollster methodology overview and evaluation - 0/10
- Referencing - 0/4
- Commits - 2/2
- Sketches - 0/2
- Simulation - 4/4
- Simulation tests - 4/4
- Actual tests - 4/4
- Parquet - 1/1
- Reproducibility - 2/4
- Miscellaneous - 0/3

Additional Comments:
None.

**Comment by wyx827** [comment]
We have fixed the issues you mentioned Thanks!
