### ISSUE TITLE
Peer Review by Onon

### ISSUE THREAD

**Issue by ononburen** [wyx827/2024USpresidentialelection#5]
**Opening statement summary:**
So far, the paper plans to use a logistic regression model to predict whether Donald Trump would win over Kamala Harris in the upcoming 2024 presidential elections. This model incorporates the variables of pollster rating, population group, numeric grade of the pollster, sample size, and methodology. 

**Strong Positive Points**

- The paper sets up the logit regression model clearly and well with the proposed functional form.
- The plan of incorporation of a Bayesian inference makes the analysis more sophisticated by  accounting for uncertainty in their predictors.
- In the functional form, each predictor and outcome variables is defined and explained.
- The appendix is done really well, revealing how the data was collected with mention of pollster used. 

**Critical improvements needed:**

- It is not clear or explicit which pollster they are using. Therefore, it is hard to tell what specific 1000 samples they are drawing from.
- Although the model and its variables are explained, it is not justified. We are only presented with the functional form without an explanation of why exactly some variables will be included in the regression and some variables are not. 
- As an extended discussion of the regression model, the methodology variable is a little confusing. Although it will likely use categorical variables to describe what the methodology was, this variable is somewhat highly correlated with sample size and numeric grade variables. There is endogeneity that needs to be accounted for in the regression.
- READme needs to be updated and the title needs to be updated. 

**Suggestions for improvement:**
- In the paper, there are chunks of code that should not be visible. For instance, page 1 is calling to tidyverse and ggplot2. 
- Explicitly state how data was processed according to the pollster. The cleaned data contains a variety of pollsters that most likely would not be used in their analysis.
- A rough sketch of the idealized methodology  of the model could help as a supplement to the appendix. 
- Data is cleaned, but it does not seem to be cleaned to the extent that will be used for the model and analysis. 
- Following up on the previous point, a more in-depth justification of each predictor and outcome variable would really help direct readers. 
- More general updates like readme and unused files  in the repo should be updated or removed. 
- Although it is inferable where the data comes from, 538 should still be cited. 

**Overall Evaluation**
For now, the paper is bare bones and a first draft. A reader can faintly tell what is trying to be done and achieved with the data. The model is a terrific start to analysis and it seems as though their plan for predicting a winner of the presidential election is solid. 

Rubric:

R citation - 1/1
Data citation - 0/1
Does not look like class paper - 0/1
LLM usage - 0/1
Title - 0/2 
Author, date, and repo - 2/2
Abstract - 0/4
Introduction - 0/4
Estimand - 1/1
Data - 8/10   *Should clean further*
Measurement - 0/4
Model - 8/10 *Justification of model needed*
Results - 0/10
Discussion - 0/10
Prose - 10/10
Cross-references - 0/1
Captions - 0/2
Graphs/tables/etc - 0/4
Idealized methodology - 10/10
Idealized survey - 3/4
Pollster methodology overview and evaluation - 10/10
Referencing - 0/4
Commits - 2/2
Sketches - 0/2
Simulation - 4/4
Simulation tests - 4/4
Actual tests - 0/4 
Parquet - 1/1
Reproducibility - 4/4
Miscellaneous - 0/3 *At the moment, not enough substance or realization of the results of the model.*

Final Result, as of this moment (2024/10/23, 5:36 P.M): 66 / 126

**Additional Comments:**
No additional comments.

**Comment by wyx827** [comment]
We have fixed the issues you mentioned Thanks!
