### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [wyx827/2024USpresidentialelection#6]
- R is appropriately cited (1/1)
	- Great.
- Data are appropriately cited (1/1)
	- Great.
- Class paper (1/1)
	- Great.
- LLM usage is documented (1/1)
	- Great.
- Title (1/2)
	- Seeing as you have a subtitle with your main finding you don't need to have a title with it also.
	- Consider how to convey uncertainty in the subtitle.
- Author, date, and repo (2/2)
	- Great
- Abstract (2/4)
	- You should acknowledge this would be a landslide.
- Introduction (2/4)
	- Be more concise.
- Estimand (0/1)
	- Just have this as a paragraph in the introduction not a subsection.
- Data (7/10)
	- Good
- Measurement (0/4)
	- The fundamental measurement problem is that you are trying to go from an opinion in someone's head about who they are going to vote for to an estimate of the number of electoral college votes they get. That does not come across here at all.
- Model (7/10)
	- Nice. Could add more detail.
- Results (7/10)
	- Why doesn't Figure 6 have a caption?
	- Consider a graph of your coefficients seeing as the table is long?
- Discussion (7/10)
	- Interesting points raised
- Prose (3/6)
	- Don't explain what the x-axis represents etc. Just talk about the content.
	- Don't say "This visualization highlights", instead say "Figure X highlights".
- Cross-references (1/1)
	- Good.
- Captions (0/2)
	- In the data section these were great. But in the model and results section they were bad.
- Graphs/tables/etc (-/4)
	- Figure 5 format needs to be changed. Don't use a line chart.
- Idealized methodology (5/10)
	- Same comment as for "Pollster methodology" below.
- Idealized survey (4/4)
	- Delightful.
- Pollster methodology overview and evaluation (5/10)
	- Please demonstrate that you know what these terms mean. What is a target population? What is a probability sample? Why does non-response matter?
- Referencing (0/4)
	- Some missing spaces with in-text citation e.g. ggplot2(Wichkam) on page 4 and page 16.
- Commits (2/2)
	- Great.
- Sketches (2/2)
	- Great.
- Simulation (3/4)
	- Be more sophisticated and add interaction between variables.
- Tests-simulation (4/4)
	- Great.
- Tests-actual (3/4)
	- Good.
- Parquet (1/1)
	- Great.
- Reproducible workflow (4/4)
	- Great.
- Miscellaneous (2/3)
	- Nice graphic on your survey
	- Attention check!

**Comment by Cassieliu77** [comment]
Hi Professor Rohan,
Thanks for your review. We have revised our paper a lot based on your feedback, especially for the measurement and methodology section.
